spring.application.name=USERSAPI

spring.mongodb.uri=mongodb+srv://MSDATASERVER_ADMIN:N3QuZb!Bv5Np-_R@msdataserver.g1q0538.mongodb.net/USERS?retryWrites=true&w=majority

server.port=8080

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.web=INFO

spring.cache.type=simple
